domain: bradylane.github.io/muzikstando-docs
url: https://bradylane.github.io/muzikstando-docs
permalink: /:title
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
